= Vim
:toc:
:toc-placement!:

toc::[]

[[reload-config]]
Reload Vim config
-----------------

`:so ~/.vimrc`

[[insert-unicode-char]]
Type a Unicode character
------------------------

To insert a check mark (U+2713) `✓` type `C-v-u2713`.

[[normal-mode]]
Normal mode
-----------

* ~ - change case (tilde operator)

[[map-keys]]
Map keys
--------

* http://vim.wikia.com/wiki/Mapping_keys_in_Vim_-__Tutorial__(Part_1)
* `:noremap` - don't recurse when expanding map
* `:map` - list all maps (normal, visual, operator-pending)
* `:imap` - list insert and replace mode maps
* `:nmap` - list normal mode maps
* `:vmap` - list visual and select mode maps
* `:smap` - list select mode maps
* `:xmap` - list visual mode maps
* `:omap` - list operator pending mode maps
* `:cmap` - list cli mode maps
* `:map!` - list insert and cli modes
* `:Imap` - list insert, cli, lang-arg modes

[[special-keys]]
Special keys
~~~~~~~~~~~~

* `help keycodes`

[[reference-manual]]
Reference manual
----------------

* `:help <arg>` or `:helpgrep <arg`
* Bookmark: quickref, usr_07.txt,
* reference_toc
* change.txt 4.4 Changing tabs ✓
* insert.txt CTRL-Q, ins-expandtab
* options.txt
** expandtab ✓

[[help]]
help
----

* `x`, `CTRL-R` - normal mode command
* `v_u` - visual mode command
* `i_<Esc>` - insert mode command
* `:quit` - command-line command
* `c_<Del>` - command-line editing
* `-r` - command-line argument for vim
* `'textwidth'` - option
* `/[` - regex
* `E37` - errors - `subject()` - functions - `+subject` - compile-time
feature

[[capture-output-of-an-external-command]]
Capture output of an external command
-------------------------------------

* http://vim.wikia.com/wiki/Append_output_of_an_external_command

[[from-inside-vim]]
From inside vim
~~~~~~~~~~~~~~~

* `:r !date` - append output of system `date` command to the current
buffer

[[from-outside-vim]]
From outside vim
~~~~~~~~~~~~~~~~

* `date | vim -`
* `vim <(ls -la)`

[[file-scrolling]]
File scrolling
--------------

* 2% - go to 2% of a file
* CTRL+b - scroll up a page
* CTRL+f - scroll down a page
* CTRL+u - scroll up half page
* CTRL+d - scroll down half page
* CTRL+y - scroll up a line
* CTRL+e - scroll down a line
* zz - scroll current line into center (__scrolloff__ option - number of
lines to pad the current line when scrolling)
* zt - scroll current line to the top
* zb - scroll current line to the bottom
* H/M/L - jump to first (home), middle, last currently seen line
* CTRL+0 - jump forward
* CTRL+I - jump backward
* `:jumps`
* `` - jump back and force between 2 positions
* set 26 marks with `ma`-`mz` and jump to them with `a-`z (marked col)
or 'a-'z (first col) _Doesn't jump across buffers_
* `:marks` (' - position before jump, " - position when last editing a
file, [ - start of last change, ] - end of last change
* Ctrl+o, Ctrl+i - jump to previous/next cursor position
* Ctrl+r;Ctrl+w (or ) - copy a word into command line

[[search-and-replace]]
Search and replace
~~~~~~~~~~~~~~~~~~

* Use `Ctrl-L` to insert next char in the match or `Ctrl-r,Ctrl-w` to
complete a word match.
* `/` - start search forward from current line. Navigate thru search
history with arrow keys (filtering works).
* `4*` - search *word* under the cursor as a Nth word
* `g*`, `g#` - search *word* under the cursor as a match
* `4n`, `4N` - N-th match after/before
* `ggn`, `GN` - first / last match
* `:%s/\n//gc` - replace newlines
* `:g/pattern` - show all lines matching the pattern
* `:g/pattern/d` - delete all lines matching a pattern (e.g. `:g/^$/d` -
deletes all empty lines)
* `:g/pattern/command` - execute a command on lines which match a regex
* `/pattern/e` - search-offset - position the cursor at the end of the
match
* `/\%d65`, `/\%x41`, `/\%u2013`, `/\%d8211` - Searching for chars by
their code value.
* `/the\C`, `/the\c` - force pattern case-(in)sensitivity

[[windows]]
windows
~~~~~~~

* `C-W` - switch between windows
* `C-W-=` - make all windows the same size
* `n-C-W-+`, `n-C-W--` - change window height, `:res +10` - same thing
* `:vertical resize +10` - change window width
* `C-W-{i,j,h,l}` - switch windows
* https://technotales.wordpress.com/2010/04/29/vim-splits-a-guide-to-doing-exactly-what-you-want/

[[vim-grepping]]
vim grepping
~~~~~~~~~~~~

* http://vim.wikia.com/wiki/Find_in_files_within_Vim
* `:grep` - populates quickfix list
* `:vimgrep` - populates quickfix list
* `:lgrep` - populates location list
* `:lvimgrep` - populates location list

[[quickfix-list]]
quickfix list
~~~~~~~~~~~~~

* `:copen` - open quickfix list
* `:cn` - go to next location in the list
* `:cp` - go to previous location in the list
* `:cclose` - close the quickfix window
* `CTRL-W K` - move quickfix window to the top

[[location-list]]
location list
~~~~~~~~~~~~~

[[regex]]
Regex
~~~~~

* `\<` - beginning of word
* `\>` - end of word
* `*` - greedy match, `\{-}` - non-greedy match
* `^` - start of line
* `$` - end of line
* `.` - any char

[[actions]]
Actions
-------

* J
* d-motion, dd
* c-motion, cc
* r-motion
* 4p
* y-motion, yy
* "__y, "__yy - yank to clipboard (only works in versions of vim that
include clipboard support)
* "*p - paste from clipboard
* u,U,CTRL-r - undoing
* R - replace mode
* ZZ,w,q<!>,e<!> - working with buffers

[[text-objects]]
Text Objects
------------

* aw - a word
* iw - inner word
* as - a sentence
* is - inner sentence

[[commands]]
Commands
--------

* `:` - navigate thru command history

[[gotchas]]
Gotchas
-------

* **Line terminator vs line separator confusion**. Vim automatically
adds a newline at the end of each file it edits. To prevent this
behaviour for file open in binary mode (`vim -b path/to/file`) we should
disable `eol` boolean configuration variable.

[[plugin-manager-for-vim]]
Plugin Manager for Vim
~~~~~~~~~~~~~~~~~~~~~~

* https://github.com/VundleVim/Vundle.vim[Vundle]
* `iskeyword` - defines what a word is
* `!rm %` - remove current file from disk
* `bd` - remove current buffer from memory

[[examples]]
Examples
^^^^^^^^

* `:%s/^\(\s*\)incrementSuspects(\(.\{-}\),.*"\(.*\)");$/\0\r\1table.error("\3", \2);/g`
Find all calls to `incrementSuspects`, remember the indentation, first
and last parameters. Add a new line preserving the indentation with a
call to `table.error` and remembered parameters.

[[gotchas-1]]
Gotchas
^^^^^^^

* Empty search will perform the last search. It works across `/`, `:s`
and `:g`. So you can search with `/` and then substitute with `:s` by
not specifying the search pattern.

[[compare]]
Compare
~~~~~~~

* See differences between the original file and the current buffer.
+
....
:w !diff % -
....

[[commands---range-substitutepatternstringcgii---gsd-delete-lines-from-65-to-126-if-cursor-is-on-line-65---d126g---65126d]]
Commands - `:range s[ubstitute]/pattern/string/cgiI` - `:g/^\s*$/d` ##
Delete lines from 65 to 126 if cursor is on line 65 - `d126G` -
`65,126d`
------------------------------------------------------------------------------------------------------------------------------------------------

* `:.,126d`
* `:,126d`

[[buffers]]
Buffers
~~~~~~~

* `:ls` or `:ls!` - list in memory buffers (`:buffers`)
* `:f` - see info about current buffer
* `:b2` - swith to second buffer
* `:b MyCl` - switch to `MyClass` file (any part of file name can match
with stronger preference for the matches from the beginning). Tab can be
used to autocomplete and to cycle thru matching names. Use Ctrl+D to
list all matching names at once.
* `:b#` - switch to previous buffer
* `:e path/to/file` - create a buffer with associated file path (if file
exists then read from it)
* `:e` - reload the current file if it was changed on disk
* `:q` - quit vim
* `:w` - save changes (`ZZ` is equal to `:wq`)
* `:w !sudo tee %` - save file requiring root priveleges
* `:saveas 'filepath'` - clone buffer and save it to a different
filepath
* `:bufdo %s/pattern/replace/ge | update` - search and replace in all
open buffers.
* http://vim.wikia.com/wiki/Easier_buffer_switching
* `vim $(find ...)` - open multiple files

[[argument-list]]
Argument list
~~~~~~~~~~~~~

* `:args **` - open all files in cwd recursively (including directory
files)
* `:arglocal`, `argc()`, `argv()`

[[copypasting-from-system-clipboard]]
Copypasting from system clipboard
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* `:set paste`

[[vim-configuration]]
Vim configuration
-----------------

* `:scriptnames`

[[mapping]]
Mapping
-------

* `:map` - list current mappings

[[management]]
Management
----------

* `:options`
* `:help local-additions`

[[snippets]]
Snippets
--------

* http://www.vim.org/scripts/script.php?script_id=1318[snippetsEmu vim
plugin]
* http://www.vim.org/scripts/script.php?script_id=2540[snipMate vim
plugin]
* http://stackoverflow.com/questions/15334/how-to-create-short-snippets-in-vim
* https://github.com/scrooloose/snipmate-snippets
* http://www.ibm.com/developerworks/library/l-vim-script-1/
* http://stackoverflow.com/questions/14954095/adding-vim-snippets
* https://github.com/honza/vim-snippets

Michael Sanders - http://www.vim.org/account/profile.php?user_id=16544 -
https://github.com/msanders/snipmate.vim

* https://github.com/jarijokinen/snipmate.vim (Fork with toUpperCase
Functionality)

[[autocompletion]]
Autocompletion
--------------

* http://stackoverflow.com/questions/5169638/autocompletion-in-vim
* http://stackoverflow.com/questions/1115876/autocompletion-in-vim
* http://stackoverflow.com/questions/5432884/vim-auto-complete-java
* https://www.reddit.com/r/vim/comments/3xlalp/java_auto_complete_in_vim/

[[builtin]]
Builtin
~~~~~~~

Works in Insert Mode - `<C-n>`

[[visual-mode]]
Visual mode
-----------

* v - char visual mode (o - jump to other side of selection)
* V - line visual mode
* CTRL-v - col visual mode (O - jump to additional 2 corners)

[[insert-mode]]
Insert Mode
-----------

* i,I,a,A,o,O - enter mode
*  or - leave mode

[[basic-commands]]
Basic commands
--------------

* `d` - delete
* `J` - join lines
* `y` - yank
* `yy` - yank line

[[shortcuts]]
Shortcuts
---------

* `C` = `c$`
* `s` = `cl`
* `S` = `^C`
* `I` = `^i`
* `A` = `$a`
* `o` = `A<CR>`
* `O` = `ko`
* `x` = `dl`
* `c<mov>` = `d<mov>i`
* `dd` = `S<ESC>J`

[[movement]]
Movement
--------

* 0 - first char in a line
* w - word start forwards
* b - word start backwards
* e - word end forwards
* ge - word end backwards
* W - white-space separated word start forwards
* B - white-space separated word start backwards
* E - white-space separated word end forwards
* gE - white-space separated word end backwards
* % - move to matching (),[],\{} or _matchpairs_ option (or find first
in a line)
* gg, 2G, G - jump to first, 2, last line
* matchpairs

[[repetitions]]
Repetitions
-----------

* `.` - repeat change
* `u` - undo
* `@:` - repeat Ex Command
* `&` - repeat substitute command
* `n` or `N` - repeat previous pattern search (`/`, `?`, `*`)
* `;` or `,` - repeat previous character search (`f`, `t`, `F`, `T`)
* `@x` - repeat macro (`qx{changes}q`)

[[indentation]]
Indentation
-----------

* `>` and `<` commands
* `>G` - increase indent from current line to end of file
* `gg=G` - reformat/reindent text
* `:args src/main/java/**/*.java | argdo execute "normal gg=G" | update`
- reindent
* Put `filetype plugin indent on` into `~/.vimrc` - enable java
indentation

[[line-terminators]]
Line Terminators
----------------

* http://stackoverflow.com/questions/5843495/what-does-m-character-mean-in-vim
* `:args src/main/java/**/*.java | argdo set ff=unix | update` - convert
all line terminators to unix (LF)

[[trailing-whitespace]]
Trailing whitespace
-------------------

* `:args src/main/java/**/*.java | argdo :%s/\s\+$//g | update` - remove
all trailing whitespace

[[syntax-highlighting]]
Syntax highlighting
-------------------

* `:syntax on`
* https://github.com/endel/vim-github-colorscheme
* http://superuser.com/questions/627636/better-syntax-highlighting-for-java-in-vim
* https://github.com/dragfire/Improved-Syntax-Highlighting-Vim
* https://github.com/github/linguist (works only on git repositories)
* https://github.com/bpdp/vim-java
* https://github.com/sentientmachine/erics_vim_syntax_and_color_highlighting[Erics
Vim syntax and color highlighting]

[[plugins]]
Plugins
-------

* https://github.com/gabrielelana/vim-markdown

[[folks]]
Folks
-----

* https://github.com/tpope

[[pathogen-by-tim-pope]]
https://github.com/tpope/vim-pathogen[Pathogen by Tim Pope]
-----------------------------------------------------------

* http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen/[Modern
Vim config with Pathogen by Tammer Saleh]
* https://lauris.github.io/vim/2014/08/21/scala-in-vim/[Scala in Vim by
Lauris Dzilums]
* http://www.mattjmorrison.com/today-i-learned/2014/10/03/learned.html
* http://www.mattjmorrison.com/today-i-learned/2014/10/15/learned.html
