= Vim
:toc:
:toc-placement!:

toc::[]

[[ex-mode]]
Ex mode
-------

[[getting-help]]
Getting help
~~~~~~~~~~~~

* `help x`, `help CTRL-R` - normal mode command
* `help v_u` - visual mode command
* `help i_<Esc>` - insert mode command
* `help :quit` - command-line command
* `help c_<Del>` - command-line editing
* `help -r` - command-line argument for vim
* `help 'textwidth'` - option
* `help /[` - regex
* `help E37` - errors
* `help subject()` - functions
* `help +subject` - compile-time feature

[[reload-config]]
Reload config
~~~~~~~~~~~~~

`:source ~/.vimrc`

[[read-from-stdin]]
Read from STDIN
~~~~~~~~~~~~~~~

* `:r !date` - append output of system `date` command to the current
buffer
* `shell> date | vim -`
* `shell> vim <(ls -la)`


[[normal-mode]]
Normal mode
-----------

[[movement]]
Movement
~~~~~~~~

* `0` - first char in a line
* `^` - first non-whitespace char in a line
* `w` - word start forwards
* `b` - word start backwards
* `e` - word end forwards
* `ge` - word end backwards
* `W` - white-space separated word start forwards
* `B` - white-space separated word start backwards
* `E` - white-space separated word end forwards
* `gE` - white-space separated word end backwards
* `%` - move to matching (),[],\{} or _matchpairs_ option (or find first
in a line)
* `gg,` `2G`, `G` - jump to first, second, last line

[[scroll]]
Scroll
~~~~~~

* `2%` - go to 2% of a file
* `CTRL+b` - scroll up a page
* `CTRL+f` - scroll down a page
* `CTRL+u` - scroll up half page
* `CTRL+d` - scroll down half page
* `CTRL+y` - scroll up a line
* `CTRL+e` - scroll down a line
* `zz` - scroll current line into center (__scrolloff__ option - number of
lines to pad the current line when scrolling)
* `zt` - scroll current line to the top
* `zb` - scroll current line to the bottom
* `H/M/L` - jump to first (home), middle, last currently seen line
* `CTRL+0` - jump forward
* `CTRL+I` - jump backward
* `:jumps`
* ```` - jump back and force between 2 positions
* `set` 26 marks with `ma`-`mz` and jump to them with `a-`z (marked col) or 'a-'z (first col) _Doesn't jump across buffers_
* `:marks` (' - position before jump, " - position when last editing a
file, [ - start of last change, ] - end of last change
* `Ctrl+o`, `Ctrl+i` - jump to previous/next cursor position
* `Ctrl+r;Ctrl+w` (or ) - copy a word into command line

[[indentation]]
Indentation
~~~~~~~~~~~

* `>` and `<` commands
* `>G` - increase indent from current line to end of file
* `gg=G` - reformat/reindent text
* `:args src/main/java/**/*.java | argdo execute "normal gg=G" | update`
- reindent
* Put `filetype plugin indent on` into `~/.vimrc` - enable java
indentation

[[actions]]
Actions
~~~~~~~
* `~` - change case (tilde operator)
* `J` - join lines
* `d-motion`, `dd`
* `c-motion`, `cc`
* `r-motion`
* `4p`
* `y-motion`, `yy`
* `u`,`U`,`CTRL-r` - undoing
* `R` - replace mode

[[insert-mode]]
Insert Mode
-----------

* `i,I,a,A,o,O` - enter from Normal mode
* `ESC` - leave mode
*  `C-v-u2713` - insert a check mark `✓` (U+2713)

[[visual-mode]]
Visual mode
-----------

* `v` - char visual mode (`o` - jump to other side of selection)
* `V` - line visual mode
* `CTRL-v` - col visual mode (`O` - jump to additional 2 corners)

[[search]]
Search
------

- `/` vs `?`, `*` vs `#` - search forwards or backwards
- `/<pattern>/e` - character and line offsets
- `/` vs `*`, `?` vs `#` - search for pattern or current word
- search character by unicode value
- `/<pattern>\c` vs `/<pattern>\C` - toggle case sensitivity
* `:g/pattern` - show all lines matching the pattern

....
" Clear last search highlighting
nnoremap <Space> :noh<cr>
....

[[replace]]
Replace
~~~~~~~

* `:%s/\n//gc` - replace newlines

[[delete]]
Delete
~~~~~~

* `:g/pattern/d` - delete all lines matching a pattern (e.g. `:g/^$/d` -
deletes all empty lines)
* `:g/pattern/command` - execute a command on lines which match a regex

[[Grep]]
Grep
----

* `:grep` - populates quickfix list
* `:vimgrep` - populates quickfix list
* `:lgrep` - populates location list
* `:lvimgrep` - populates location list

[[quickfix-list]]
Quickfix list
~~~~~~~~~~~~~

* `:copen` - open quickfix list
* `:cn` - go to next location in the list
* `:cp` - go to previous location in the list
* `:cclose` - close the quickfix window
* `CTRL-W K` - move quickfix window to the top

[[location-list]]
Location list
~~~~~~~~~~~~~

[[regex]]
Regex
~~~~~

* `\<` - beginning of word
* `\>` - end of word
* `*` - greedy match, `\{-}` - non-greedy match
* `^` - start of line
* `$` - end of line
* `.` - any char

[[windows]]
Windows
-------

* `C-W` - switch between windows
* `C-W-=` - make all windows the same size
* `n-C-W-+`, `n-C-W--` - change window height, `:res +10` - same thing
* `:vertical resize +10` - change window width
* `C-W-{i,j,h,l}` - switch windows

[[buffers]]
Buffers
-------

* `bd` - remove current buffer from memory
* `:ls` or `:ls!` - list in memory buffers (`:buffers`)
* `:f` - see info about current buffer
* `:b2` - swith to second buffer
* `:b MyCl` - switch to `MyClass` file (any part of file name can match
with stronger preference for the matches from the beginning). Tab can be
used to autocomplete and to cycle thru matching names. Use Ctrl+D to
list all matching names at once.
* `:b#` - switch to previous buffer
* `:e path/to/file` - create a buffer with associated file path (if file
exists then read from it)
* `:e` - reload the current file if it was changed on disk
* `:q` - quit vim
* `:w` - save changes (`ZZ` is equal to `:wq`)
* `:w !sudo tee %` - save file requiring root priveleges
* `:saveas 'filepath'` - clone buffer and save it to a different
filepath
* `:bufdo %s/pattern/replace/ge | update` - search and replace in all
open buffers.
* `vim $(find ...)` - open multiple files

[[text-objects]]
Text Objects
------------

* `aw` - a word
* `iw` - inner word
* `as` - a sentence
* `is` - inner sentence

[[formatting]]
Formatting
----------

* **Line terminator vs line separator confusion**. Vim automatically
adds a newline at the end of each file it edits. To prevent this
behaviour for file open in binary mode (`vim -b path/to/file`) we should
disable `eol` boolean configuration variable.

[[shelling-out]]
Shelling out
------------
* `!rm %` - remove current file from disk

[[version-history]]
Version history
---------------

See differences between the original file and the current buffer.

....
:w !diff % -
....

[[argument-list]]
Argument list
-------------

* `:args **` - open all files in cwd recursively (including directory
files)
* `:arglocal`, `argc()`, `argv()`

[[copypasting-from-system-clipboard]]
Copypasting from system clipboard
---------------------------------

* `:set paste`

[[vim-configuration]]
Vim configuration
-----------------

* `:scriptnames`

[[mapping]]
Mapping
-------

* `:map` - list current mappings

[[management]]
Management
----------

* `:options`
* `:help local-additions`

[[autocompletion]]
Autocompletion
--------------

Works in Insert Mode - `<C-n>`

[[shortcuts]]
Shortcuts
---------

* `C` = `c$`
* `s` = `cl`
* `S` = `^C`
* `I` = `^i`
* `A` = `$a`
* `o` = `A<CR>`
* `O` = `ko`
* `x` = `dl`
* `c<mov>` = `d<mov>i`
* `dd` = `S<ESC>J`

[[repetitions]]
Repetitions
-----------

* `.` - repeat change
* `u` - undo
* `@:` - repeat Ex Command
* `&` - repeat substitute command
* `n` or `N` - repeat previous pattern search (`/`, `?`, `*`)
* `;` or `,` - repeat previous character search (`f`, `t`, `F`, `T`)
* `@x` - repeat macro (`qx{changes}q`)

[[line-terminators]]
Line Terminators
----------------

* `:args src/main/java/**/*.java | argdo set ff=unix | update` - convert
all line terminators to unix (LF)

[[trailing-whitespace]]
Trailing whitespace
-------------------

* `:args src/main/java/**/*.java | argdo :%s/\s\+$//g | update` - remove
all trailing whitespace

[[syntax-highlighting]]
Syntax highlighting
-------------------

* `:syntax on`
