#!/usr/bin/env sh

# exec name
basename="${1%.*}"
libs=$2

# build
as -o ${basename}.o $1
ld -dynamic-linker /lib64/ld-linux-x86-64.so.2 $libs -o ${basename} ${basename}.o

# run
./${basename}

# cleanup
rm ${basename}.o
rm ${basename}
