Recursively list all non-hidden files

[source,shell]
----
find . -not -path '*/\.*'
----

[[examples]]
Examples
~~~~~~~~

* `% find [files...] [options...] [expression]` - Expressions consist of
__tests__, __operators__, _actions_
* `% find /usr/local/doc -name '*.texi'` - `-name` and `-iname` match
only base names whereas `-path` match the whole path.
* `% find /usr/src -name '*.c' -size +100k -print` - prints the names of
all files rooted in `/usr/src` whose name ends with ‘.c’ and that are
larger than 100 KiB. (use `-100k` for _less than_ and `100k` for
**equals**.
* `% find . -iregex '.*[2-9].*' -print0 | xargs -0 rm` - lets xargs
handle filenames with spaces correctly
* `% find . -iname *.yml` - find all `.yml` files in the cwd
* `% find . -type f` - find all files which are not directories.
* `% find

[[supported-regex-syntaxes]]
Supported regex syntaxes
~~~~~~~~~~~~~~~~~~~~~~~~

* switch with `-regextype`
* `emacs` (default), `posix-awk`, `posix-basic`, `posix-egrep`,
`posix-extended`

[[find-all-links-to-sysdep.c-in-the-cwd]]
Find all links to sysdep.c in the cwd
-------------------------------------

....
find . -lname '*sysdep.c'
....

[[delete-files]]
Delete files
------------

....
find /path -type f -delete
find /path -type f -exec rm {} \;
find /path -type f -print0 | xargs -0 rm
find /path -type f -print0 | xargs -0 -I '{}'  rm '{}'
find /path -type f | while read file; do rm $file; done
find /path -type f | tr '\n' '\0' | xargs -0 rm
....

[[ls-like-output-with-inode-numbers]]
ls-like output with inode numbers
---------------------------------

....
find src -ls
....

....
find . -name \*.java | tr '\n' '\0' | xargs -0 wc
find . -name \*.xml | grep -v /workspace/ | tr '\n' '\0' | xargs -0 tar -cf xml.tar
....

[[exlude-git-directory]]
exlude git directory
--------------------

....
vim $(find notes recipes -type f -not -path "**.git**")
....

* http://stackoverflow.com/questions/4210042/exclude-directory-from-find-command

[[xargs]]
xargs
-----

The name xargs, pronounced EX-args, means "combine arguments." `xargs`
builds and executes command lines by gathering together arguments it
reads on the standard input. Most often, these arguments are lists of
file names generated by `find`.

* `% xargs [option...] [command [initial-arguments]]`
* `% xargs grep typedef < file-list`- searches the files listed in the
file file-list and prints all of the lines in them that contain the word
'typedef'
* http://stackoverflow.com/questions/31735780/using-export-f-with-xargs-not-working?lq=1[SO
- calling shell function in xargs]
* http://stackoverflow.com/questions/11232782/using-a-user-defined-bash-function-in-xargs?lq=1[SO
- similar]
* http://stackoverflow.com/questions/11003418/calling-functions-with-xargs-within-a-bash-script[SO
- similar]
