= Filesystem
:toc:
:toc-placement!:

toc::[]

[[system-calls]]
System calls
------------

* open
* lstat
* fstat
* chmod
* chown
* umask
* mount
* fcntl

[[resources]]
Resources
---------

* https://www.thomas-krenn.com/en/wiki/Linux_Storage_Stack_Diagram[Linux
Storage Stack Diagram by by Fischer and Shonberger]

[[concepts]]
Concepts
--------

* Linux Virtual Filesystem (VFS) - API
* Linux inode cache is implemented in a single file, fs/inode.c
* superblock - a record of the characteristics of a filesystem
** size
** block size
** empty and filled blocks and their respective counts
** size and location of inode tables
** disk block map and usage information
** size of block groups

On UNIX systems, moving a directory within the same partition generally
consists of renaming the directory.

Filesystem access is not automatically synchronized. Each process/thread
maintains its own access mode and cursor in the file and unaware of
other processes/threads.

* https://en.wikipedia.org/wiki/Inode[inode in wikipedia]

[[resources-1]]
Resources
---------

* https://docs.fedoraproject.org/en-US/Fedora/14/html/Storage_Administration_Guide/index.html[Storage
Administration Guide in Fedora Docs]

[[programming-files]]
Programming files
-----------------

* streaming vs bulk reads
* use buffered IO (deferred execution)
* use caches
* async IO
* minimize accesses (bulk reads/writes)
* random-access files, sequential access
* seekable file streams

[[file-attributes]]
file attributes
---------------

* name
* size
* type (regular, directory, symlink)
* creation time (ctime)
* last modified time (mtime)
* last access time (atime)
* file owner
* group owner
* access permissions (bit mask) (POSIX)
* is hidden

[[file-types]]
file types
----------

* softlink
* hardlink
* directory
* socket
* regular file

[[file-systems]]
file systems
------------

File system is a kernel driver - ntfs - hpfs+ - zfs - dos

[[ext4-inode]]
ext4 (inode)
~~~~~~~~~~~~

* https://docs.fedoraproject.org/en-US/Fedora/14/html/Storage_Administration_Guide/newfilesys-ext4.html[The
Ext4 File System in Fedora Docs]
* http://kernelnewbies.org/Ext4[Ext4 - kernel newbies]
* https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Storage_Administration_Guide/ch-ext4.html[Ext4
- Red Hat]
* https://en.wikipedia.org/wiki/Ext4[Ext4 - wikipedia]
* https://ext4.wiki.kernel.org/index.php/Main_Page[Ext4 - kernel archive
wiki]
* `man ext4`
* http://e2fsprogs.sourceforge.net[e2fsprogs] - utilities for
maintaining ext2, ext3 and ext4 file systems
** `mke2fs`
** `resize2fs`
** `e2fsck`
** `debugfs`
** `tune2fs`
** `dumpe2fs` - prints the super block and blocks group information for
the filesystem present on device.

[[file-system-operations]]
file system operations
----------------------

* syntactic file path operations (don't access file system)
* glob pattern
* file change notification (watching)

[[posix]]
POSIX
-----

* `/etc/fstab`

[[file-system-layout-linux-filesystem-hierarchy-standard]]
file system layout (Linux filesystem hierarchy standard)
--------------------------------------------------------

[[storage-devices]]
Storage Devices
---------------

[[security]]
Security
--------

* CWE-367: Time-of-check Time-of-use (TOCTOU) Race Condition
https://cwe.mitre.org/data/definitions/367.html

[[recovery]]
Recovery
--------

* http://unix.stackexchange.com/questions/48200/recovered-deleted-files-on-mac-by-command-line
* https://www.quora.com/Unix-Commands-What-are-some-easy-ways-to-recover-files-from-rm-rf
* http://unix.stackexchange.com/questions/48200/recovered-deleted-files-on-mac-by-command-line
* http://unix.stackexchange.com/questions/101237/how-to-recover-files-i-deleted-now-by-running-rm

[[commands]]
Commands
--------

* fsck

[[library-functions]]
Library functions
-----------------

* ftok

[[file-path]]
File Path
---------

_gnu coreutils_ - `basename` - `dirname` - `pathchk` - `mktemp` -
`realpath`

[[print-all-bytes-of-a-file-with-character-mappings]]
Print all bytes of a file with character mappings
-------------------------------------------------

* `hexdump -c file.txt`

[[distributed-file-systems]]
Distributed file systems
------------------------
